### PR TITLE
Update bigbutton.html

### PR DESCRIPTION
**Pull request by sharingan-in**
earlier,when we click on the custom button ,a black border appears around the button because the outline property is not set to zero.
after editing this file we can remove the black border outline,which gives it more click feeling on button

### CODE REVIEW

**Comment by samdroid-apps** [comment]
Thanks for the patch @SamWinchester!
- How do I reproduce this?  Please include a screenshot.
- Maybe if this happens for all buttons, this should be a patch for github.com/sugarlabs/sugar-web

**Comment by sharingan-in** [comment]
This is bigbutton.html before mentioning the outline property "https://cloud.githubusercontent.com/assets/5520697/11916940/5353df94-a715-11e5-8841-3f9f4f56588f.png "

after mentioning the outline property (https://cloud.githubusercontent.com/assets/5520697/11916949/9d47d164-a715-11e5-87c8-4df577ebd3a7.png)
For adding this property check the 27th line of the following screenshot
(https://cloud.githubusercontent.com/assets/5520697/11916961/8e57d04a-a716-11e5-9125-0ac220f5ec7b.png)
The outline property only comes to the picture when we change the border-radius of any html entity,otherwise border and the outline are same

**Comment by samdroid-apps** [comment]
great!  I think that this really should be in the sugar-web toolkit though, as it applies to all sugar web activities!

**Comment by sharingan-in** [comment]
yes, the outline property is  defined only  for the input tag in sugar.css and not for any other entity

**Pull request closed without merging**
